import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config({ path: join(__dirname, "..", ".env") });

import Subject from "../models/Subject.js";
import Chapter from "../models/Chapter.js";
import Simulation from "../models/Simulation.js";

/* ═══════════════════════════════════════════════════════════════════
 *  Seed Data — populates MongoDB with the full taxonomy
 * ═══════════════════════════════════════════════════════════════════ */

const subjects = [
  {
    slug: "mathematics",
    title: "Mathematics",
    eyebrow: "See the pattern",
    heroTitle: "Turn equations and geometry into living visual stories.",
    description: "Learners explore dynamic triangles and algebraic balance with real-time feedback that makes abstract ideas concrete.",
    accent: "from-amber-300 via-orange-300 to-rose-300",
    glow: "bg-amber-100",
    icon: "calculator",
    highlights: ["Pythagorean visualizer", "Balancing scale", "Instant calculations"],
    hasSubcategories: false,
    subcategories: [],
    order: 1,
  },
  {
    slug: "science",
    title: "Science",
    eyebrow: "Observe, test, explain",
    heroTitle: "Run vivid chemistry, biology, and physics labs from any classroom.",
    description: "Students can mix chemicals, wire circuits, and place organelles inside premium light-theme simulations built for hands-on understanding.",
    accent: "from-sky-400 via-cyan-400 to-emerald-400",
    glow: "bg-sky-100",
    icon: "beaker",
    highlights: ["Chemistry mixing lab", "Circuit builder", "Cell anatomy map"],
    hasSubcategories: true,
    subcategories: [
      { slug: "physics", title: "Physics", icon: "atom", description: "Forces, motion, electricity, and energy", order: 1 },
      { slug: "chemistry", title: "Chemistry", icon: "flask-conical", description: "Reactions, elements, and molecular structures", order: 2 },
      { slug: "biology", title: "Biology", icon: "dna", description: "Cells, organisms, and ecosystems", order: 3 },
    ],
    order: 2,
  },
  {
    slug: "social-science",
    title: "Social Science",
    eyebrow: "Connect people, place, and power",
    heroTitle: "Match maps, order events, sort civic roles, and classify economic activity with confidence.",
    description: "Interactive geography, history, civics, and economics games help students understand chronology, institutions, global awareness, and economic sectors.",
    accent: "from-emerald-300 via-lime-300 to-yellow-300",
    glow: "bg-emerald-100",
    icon: "globe-2",
    highlights: ["Map matching", "Economics sector sort", "Timeline builder"],
    hasSubcategories: true,
    subcategories: [
      { slug: "geography", title: "Geography", icon: "map-pin", description: "Maps, landforms, and climate patterns", order: 1 },
      { slug: "history", title: "History", icon: "scroll-text", description: "Events, timelines, and historical movements", order: 2 },
      { slug: "civics", title: "Civics", icon: "landmark", description: "Government, rights, and civic responsibilities", order: 3 },
      { slug: "economics", title: "Economics", icon: "trending-up", description: "Markets, sectors, and financial literacy", order: 4 },
    ],
    order: 3,
  },
  {
    slug: "language",
    title: "Language",
    eyebrow: "Express, connect, create",
    heroTitle: "Master Hindi and English through interactive grammar, vocabulary, and comprehension labs.",
    description: "Students build sentences, explore word families, and practice comprehension skills through gamified visual exercises instead of rote memorization.",
    accent: "from-violet-400 via-purple-400 to-fuchsia-400",
    glow: "bg-violet-100",
    icon: "book-open-text",
    highlights: ["Sentence builder", "Grammar lab", "Vocabulary explorer"],
    hasSubcategories: true,
    subcategories: [
      { slug: "hindi", title: "Hindi", icon: "languages", description: "व्याकरण, शब्द भंडार, और वाक्य रचना", order: 1 },
      { slug: "english", title: "English", icon: "pen-line", description: "Grammar, vocabulary, and reading comprehension", order: 2 },
    ],
    order: 4,
  },
];

const simulations = [
  {
    slug: "chemistry-lab",
    title: "Chemistry Reaction Bench",
    summary: "Combine two reagents, inspect the balanced equation, and distinguish between dissolution, neutralization, precipitation, and gas evolution.",
    topic: "Chemistry",
    challenge: "Make NaCl + H₂O accurately",
    estimatedTime: "7-9 min",
    accent: "from-sky-400 to-emerald-400",
    componentKey: "ChemistryLab",
    subjectSlug: "science",
    subcategorySlug: "chemistry",
    subjectLabel: "Science",
    instructions: [
      "Choose two samples from the chemistry bench.",
      "Place one sample into Beaker A and one into Beaker B.",
      "Read the equation, products, and observation panel before pressing check.",
      "Use the feedback to identify the accurate pair that produces sodium chloride and water.",
    ],
    tags: ["chemistry", "reactions", "equations"],
  },
  {
    slug: "circuit-builder",
    title: "Closed Circuit Workbench",
    summary: "Assemble a real energy pathway with a source, conductor, switch, and load, then diagnose why current does or does not flow.",
    topic: "Physics",
    challenge: "Light the lamp",
    estimatedTime: "7-9 min",
    accent: "from-indigo-400 to-amber-300",
    componentKey: "CircuitBuilder",
    subjectSlug: "science",
    subcategorySlug: "physics",
    subjectLabel: "Science",
    instructions: [
      "Choose a source, a path material, a switch state, and an output device.",
      "Place one part into each workbench slot to complete the circuit plan.",
      "Watch the schematic update to show whether the loop is open, insulating, or closed.",
      "Check the circuit to confirm that the lamp glows.",
    ],
    tags: ["physics", "electricity", "circuits"],
  },
  {
    slug: "cell-anatomy",
    title: "Cell Anatomy Map",
    summary: "Place the nucleus, mitochondria, ribosomes, ER, and Golgi apparatus into the correct organelle zones.",
    topic: "Biology",
    challenge: "Map all five organelles",
    estimatedTime: "5-6 min",
    accent: "from-emerald-400 to-cyan-300",
    componentKey: "CellAnatomy",
    subjectSlug: "science",
    subcategorySlug: "biology",
    subjectLabel: "Science",
    instructions: [
      "Choose an organelle card from the tray below the cell model.",
      "Drop it into the matching highlighted zone inside the cell membrane.",
      "Use the check button to verify placements.",
      "Reset the board to practice again.",
    ],
    tags: ["biology", "cells", "organelles"],
  },
  {
    slug: "pythagorean-visualizer",
    title: "Right Triangle Builder",
    summary: "Drag side lengths onto a triangle model, compare square areas, and build a valid Pythagorean triple.",
    topic: "Geometry",
    challenge: "Build c = 10",
    estimatedTime: "6-8 min",
    accent: "from-amber-400 to-rose-400",
    componentKey: "PythagoreanVisualizer",
    subjectSlug: "mathematics",
    subcategorySlug: null,
    subjectLabel: "Mathematics",
    instructions: [
      "Choose three side lengths from the number bank.",
      "Drop one value on each side label for a, b, and c.",
      "Compare a² + b² with c² in the live theorem panel.",
      "Check the triangle once you believe it's a valid right triangle.",
    ],
    tags: ["mathematics", "geometry", "pythagorean"],
  },
  {
    slug: "algebra-balance",
    title: "Interactive Balancing Scale",
    summary: "Drag number weights onto both pans and solve the equation x + 2 = 5 by balancing the scale.",
    topic: "Algebra",
    challenge: "Solve for x",
    estimatedTime: "5-7 min",
    accent: "from-orange-300 to-amber-500",
    componentKey: "AlgebraBalance",
    subjectSlug: "mathematics",
    subcategorySlug: null,
    subjectLabel: "Mathematics",
    instructions: [
      "Use the number cards to choose a value for x.",
      "Drop weights into the x slot and right pan slot.",
      "Watch the beam tilt in response to weight.",
      "Check the scale to confirm your answer.",
    ],
    tags: ["mathematics", "algebra", "equations"],
  },
  {
    slug: "geography-match",
    title: "Map Matching Game",
    summary: "Match continent name labels to simplified SVG silhouettes on a world-map atlas.",
    topic: "Geography",
    challenge: "Label all continents",
    estimatedTime: "5-6 min",
    accent: "from-emerald-400 to-lime-300",
    componentKey: "GeographyMatch",
    subjectSlug: "social-science",
    subcategorySlug: "geography",
    subjectLabel: "Social Science",
    instructions: [
      "Drag or tap-select a continent label from the card tray.",
      "Place the label on the matching outline.",
      "Check the full map once all slots are filled.",
      "Use feedback to adjust labels.",
    ],
    tags: ["geography", "continents", "maps"],
  },
  {
    slug: "history-timeline",
    title: "Freedom to Republic Timeline",
    summary: "Arrange key milestones from the Revolt of 1857 through the Constitution of India in chronological order.",
    topic: "History",
    challenge: "Build the chronology",
    estimatedTime: "7-9 min",
    accent: "from-lime-400 to-yellow-300",
    componentKey: "HistoryTimeline",
    subjectSlug: "social-science",
    subcategorySlug: "history",
    subjectLabel: "Social Science",
    instructions: [
      "Read each event card carefully.",
      "Drag the cards into the numbered timeline slots.",
      "Review before checking the full sequence.",
      "Clear slots and rebuild if incorrect.",
    ],
    tags: ["history", "india", "timeline"],
  },
  {
    slug: "civics-sort",
    title: "Government Responsibilities Sort",
    summary: "Sort key responsibilities into Legislature, Executive, and Judiciary buckets.",
    topic: "Civics",
    challenge: "Sort the branches",
    estimatedTime: "6-7 min",
    accent: "from-emerald-500 to-yellow-400",
    componentKey: "CivicsSort",
    subjectSlug: "social-science",
    subcategorySlug: "civics",
    subjectLabel: "Social Science",
    instructions: [
      "Choose a responsibility card from the unsorted tray.",
      "Drop the card into the correct government branch.",
      "Check to validate all assignments.",
      "Use hints to refine buckets.",
    ],
    tags: ["civics", "government", "democracy"],
  },
  {
    slug: "economics-sector-sort",
    title: "Economic Sectors Sort",
    summary: "Sort occupations and activities into the primary, secondary, and tertiary sectors.",
    topic: "Economics",
    challenge: "Sort the sectors",
    estimatedTime: "6-7 min",
    accent: "from-emerald-400 via-lime-300 to-yellow-300",
    componentKey: "EconomicsSectorSort",
    subjectSlug: "social-science",
    subcategorySlug: "economics",
    subjectLabel: "Social Science",
    instructions: [
      "Choose an occupation or activity card.",
      "Place it into the correct sector.",
      "Continue until all cards are sorted.",
      "Check to confirm every activity is grouped correctly.",
    ],
    tags: ["economics", "sectors", "occupation"],
  },
  {
    slug: "hindi-sentence-builder",
    title: "वाक्य रचना — Sentence Builder",
    summary: "Arrange Hindi words in correct grammatical order to form meaningful sentences.",
    topic: "Hindi",
    challenge: "Build 3 correct sentences",
    estimatedTime: "6-8 min",
    accent: "from-violet-400 to-fuchsia-400",
    componentKey: "HindiSentenceBuilder",
    subjectSlug: "language",
    subcategorySlug: "hindi",
    subjectLabel: "Language",
    instructions: [
      "Read the English meaning of the target sentence.",
      "Choose Hindi word cards from the shuffled tray.",
      "Arrange them in the correct grammatical order.",
      "Check to verify the sentence.",
    ],
    tags: ["hindi", "grammar", "sentence"],
  },
  {
    slug: "english-grammar-sort",
    title: "Parts of Speech Lab",
    summary: "Classify words into nouns, verbs, adjectives, and adverbs by sorting them into grammar buckets.",
    topic: "English",
    challenge: "Sort all 12 words",
    estimatedTime: "5-7 min",
    accent: "from-purple-400 to-indigo-400",
    componentKey: "EnglishGrammarSort",
    subjectSlug: "language",
    subcategorySlug: "english",
    subjectLabel: "Language",
    instructions: [
      "Read each word card and determine its part of speech.",
      "Drag the card into the matching bucket.",
      "Continue until all word cards are classified.",
      "Check to see which words were correctly sorted.",
    ],
    tags: ["english", "grammar", "parts-of-speech"],
  },
];

const chapters = [
  {
    slug: "circuit-basics",
    title: "Electric Circuits",
    description: "Build a closed circuit with a battery, conductor, switch, and bulb.",
    subjectSlug: "science",
    subcategorySlug: "physics",
    classLevel: 8,
    order: 1,
    simulationSlug: "circuit-builder",
    estimatedTime: "7-9 min",
    difficulty: "intermediate",
    learningObjectives: ["Identify circuit parts", "Distinguish conductors from insulators", "Explain switch function"],
    isPublished: true,
  },
  {
    slug: "chemical-reactions",
    title: "Chemical Reaction Bench",
    description: "Combine reagents and classify chemical reactions by type.",
    subjectSlug: "science",
    subcategorySlug: "chemistry",
    classLevel: 8,
    order: 1,
    simulationSlug: "chemistry-lab",
    estimatedTime: "7-9 min",
    difficulty: "intermediate",
    learningObjectives: ["Write balanced equations", "Classify reactions", "Predict products"],
    isPublished: true,
  },
  {
    slug: "cell-structure",
    title: "Cell Anatomy Map",
    description: "Place organelles into the correct zones inside a cell.",
    subjectSlug: "science",
    subcategorySlug: "biology",
    classLevel: 7,
    order: 1,
    simulationSlug: "cell-anatomy",
    estimatedTime: "5-6 min",
    difficulty: "beginner",
    learningObjectives: ["Name five key organelles", "Describe organelle functions", "Compare plant and animal cells"],
    isPublished: true,
  },
  {
    slug: "pythagorean-theorem",
    title: "Right Triangle Builder",
    description: "Build Pythagorean triples and visualize the theorem.",
    subjectSlug: "mathematics",
    subcategorySlug: null,
    classLevel: 8,
    order: 1,
    simulationSlug: "pythagorean-visualizer",
    estimatedTime: "6-8 min",
    difficulty: "intermediate",
    learningObjectives: ["Apply the Pythagorean theorem", "Identify valid triples", "Visualize area squares"],
    isPublished: true,
  },
  {
    slug: "linear-equations",
    title: "Interactive Balancing Scale",
    description: "Solve linear equations by balancing a visual scale.",
    subjectSlug: "mathematics",
    subcategorySlug: null,
    classLevel: 6,
    order: 1,
    simulationSlug: "algebra-balance",
    estimatedTime: "5-7 min",
    difficulty: "beginner",
    learningObjectives: ["Understand equations as balance", "Solve single-variable equations", "Use inverse operations"],
    isPublished: true,
  },
  {
    slug: "continents-oceans",
    title: "Map Matching Game",
    description: "Match continent labels to their silhouettes.",
    subjectSlug: "social-science",
    subcategorySlug: "geography",
    classLevel: 6,
    order: 1,
    simulationSlug: "geography-match",
    estimatedTime: "5-6 min",
    difficulty: "beginner",
    learningObjectives: ["Identify seven continents", "Associate shapes with names", "Develop spatial awareness"],
    isPublished: true,
  },
  {
    slug: "indian-freedom-struggle",
    title: "Freedom to Republic Timeline",
    description: "Arrange key milestones of Indian independence chronologically.",
    subjectSlug: "social-science",
    subcategorySlug: "history",
    classLevel: 8,
    order: 1,
    simulationSlug: "history-timeline",
    estimatedTime: "7-9 min",
    difficulty: "intermediate",
    learningObjectives: ["Sequence independence events", "Understand cause-effect", "Build chronological reasoning"],
    isPublished: true,
  },
  {
    slug: "branches-of-government",
    title: "Government Responsibilities Sort",
    description: "Sort responsibilities across Legislature, Executive, and Judiciary.",
    subjectSlug: "social-science",
    subcategorySlug: "civics",
    classLevel: 7,
    order: 1,
    simulationSlug: "civics-sort",
    estimatedTime: "6-7 min",
    difficulty: "intermediate",
    learningObjectives: ["Name three branches", "Classify responsibilities", "Understand separation of powers"],
    isPublished: true,
  },
  {
    slug: "economic-sectors",
    title: "Economic Sectors Sort",
    description: "Sort occupations into primary, secondary, and tertiary sectors.",
    subjectSlug: "social-science",
    subcategorySlug: "economics",
    classLevel: 9,
    order: 1,
    simulationSlug: "economics-sector-sort",
    estimatedTime: "6-7 min",
    difficulty: "intermediate",
    learningObjectives: ["Define three sectors", "Classify occupations", "Understand economic organization"],
    isPublished: true,
  },
  {
    slug: "hindi-sentence-builder",
    title: "वाक्य रचना — Sentence Builder",
    description: "Arrange Hindi words in correct SOV grammatical order.",
    subjectSlug: "language",
    subcategorySlug: "hindi",
    classLevel: 5,
    order: 1,
    simulationSlug: "hindi-sentence-builder",
    estimatedTime: "6-8 min",
    difficulty: "beginner",
    learningObjectives: ["Construct Hindi sentences", "Identify subject-verb-object", "Practice word order"],
    isPublished: true,
  },
  {
    slug: "english-grammar-lab",
    title: "Parts of Speech Lab",
    description: "Classify words into nouns, verbs, adjectives, and adverbs.",
    subjectSlug: "language",
    subcategorySlug: "english",
    classLevel: 5,
    order: 1,
    simulationSlug: "english-grammar-sort",
    estimatedTime: "5-7 min",
    difficulty: "beginner",
    learningObjectives: ["Identify parts of speech", "Classify by function", "Build vocabulary awareness"],
    isPublished: true,
  },
];

/* ── Run Seed ── */
async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    await Subject.deleteMany({});
    await Chapter.deleteMany({});
    await Simulation.deleteMany({});
    console.log("🗑️  Cleared existing collections");

    // Insert
    await Subject.insertMany(subjects);
    console.log(`📚 Inserted ${subjects.length} subjects`);

    await Simulation.insertMany(simulations);
    console.log(`🧪 Inserted ${simulations.length} simulations`);

    await Chapter.insertMany(chapters);
    console.log(`📖 Inserted ${chapters.length} chapters`);

    console.log("\n✅ Seed complete!");
    process.exit(0);
  } catch (err) {
    console.error("❌ Seed failed:", err.message);
    process.exit(1);
  }
}

seed();
